### ISSUE TITLE
Do not open files as FIFO if they are regular files

### ISSUE THREAD

**Issue by clonejo** [ibabushkin/bartender#3]
Just don't open the file (so the default value stays in the buffer) and write an error to stderr.

Such a check is small, but vastly improves the user experience (poll always returns immediately, creating immense cpu load).

**Comment by ibabushkin** [comment]
Ah, that makes sense. Should be easy enought to implement, you're right.

**Comment by ibabushkin** [comment]
Should be fixed now, check is in place.
